# Generated by Django 2.2.6 on 2020-01-03 04:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HSSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 3, 4, 2, 28, 930250)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 3, 4, 2, 28, 930788)),
        ),
        migrations.AlterField(
            model_name='order',
            name='workername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSSapp.Profile'),
        ),
    ]
